Updating with RSA creation script

diff --git a/0x0B-ssh/1-create_ssh_key_pair b/0x0B-ssh/1-create_ssh_key_pair
--- a/0x0B-ssh/1-create_ssh_key_pair
+++ b/0x0B-ssh/1-create_ssh_key_pair
@@ -7,4 +7,9 @@ KEY_NAME="school"
 BITS=4096
 PASSPHRASE="betty"
 
-ssh-keygen -t rsa -b $BITS -N $PASSPHRASE -f ~/.ssh/$KEY_NAME
+if [ -f ~/.ssh/$KEY_NAME]; then
+	echo "Key '$KEY_NAME' already exists. Aborting."
+	exit 1
+fi
+
+ssh-keygen -b $BITS -t rsa -f ~/.ssh/$KEY_NAME -N "$PASSPHRASE"
